apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica-set
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod1
      labels:
        app: nginx
        env: dev
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: front-end

