apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: dev
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
