apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: local-storage
  volumeName: my-persistent-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
